when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: restore-cache
    failure: ignore
    image: plugins/cache:1.10@sha256:1ff8584ff4e1d245fbb5e19350901c8f995cf2f32f2618f687445e8535003121
    settings:
      access_key:
        from_secret: garage_s3_access_key
      secret_key:
        from_secret: garage_s3_secret_key
      restore: true
      backend: s3
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: buildkit-cache
      region: garage
      path_style: true
      archive_format: zstd
      cache_key: "netzbremse-{{ checksum \"go.sum\" }}-{{ checksum \"package-lock.json\" }}"
      mount:
        - .go-mod-cache
        - .npm-cache

  - name: go-test
    image: dhi.io/golang:1.26.7-debian13-dev@sha256:0ff9ace4c61aa79a6b6d039a0268884c4fffe253e480fe2449d055da7b88b579
    environment:
      GOMODCACHE: /woodpecker/src/git.m0sh1.cc/m0sh1/netzbremse/.go-mod-cache
    commands:
      - mkdir -p .go-mod-cache
      - go test ./...

  - name: browser-script-check
    image: dhi.io/node:26.6.0-0-debian13-dev@sha256:5d10000364e6afe9d9fb92b9371eb7fb09564a4dd77f88c52dd90be81af7ff3f
    commands:
      - node --check scripts/netzbremse-browser.mjs

  - name: rebuild-cache
    failure: ignore
    image: plugins/cache:1.10@sha256:1ff8584ff4e1d245fbb5e19350901c8f995cf2f32f2618f687445e8535003121
    settings:
      access_key:
        from_secret: garage_s3_access_key
      secret_key:
        from_secret: garage_s3_secret_key
      rebuild: true
      backend: s3
      endpoint: http://garage.garage.svc.cluster.local:3900
      bucket: buildkit-cache
      region: garage
      path_style: true
      archive_format: zstd
      cache_key: "netzbremse-{{ checksum \"go.sum\" }}-{{ checksum \"package-lock.json\" }}"
      mount:
        - .go-mod-cache
        - .npm-cache
